# Production Environment Overrides

environment: "production"
debug: false
log_level: "INFO"

mcp:
  server:
    host: "0.0.0.0"
    port: 8000
    max_connections: 1000

frameworks:
  crewai:
    verbose: false
  
  langgraph:
    checkpointer: "redis"
  
  autogen:
    temperature: 0.7

tools:
  rate_limiting:
    per_minute: 120
    burst: 20
  
  retry:
    max_attempts: 5
    max_delay: 300.0
  
  content:
    timeout: 60

monitoring:
  metrics:
    enabled: true
  
  health_checks:
    enabled: true
    interval: 15
  
  tracing:
    enabled: true
    sample_rate: 0.1

logging:
  console:
    level: "WARNING"
  
  file:
    enabled: true
    level: "INFO"
  
  framework_specific:
    crewai:
      level: "INFO"
    langgraph:
      level: "INFO"
    autogen:
      level: "INFO"